#ifndef LIBQMETAOBJECT_GLOBAL_H
#define LIBQMETAOBJECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQMETAOBJECT_LIBRARY)
#  define LIBQMETAOBJECT_EXPORT Q_DECL_EXPORT
#else
#  define LIBQMETAOBJECT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQMETAOBJECT_GLOBAL_H
